### ISSUE TITLE
FTIR Tooltips

### ISSUE THREAD

**Issue by Brennaser** [RastonLab/Virtual-FTIR-Spectrometer#23]

**Comment by VanFossen** [comment]
Initially we were going to use a similar setup to the HeNDI (click and tooltips appear on the side or at the bottom of the page).

After talking with Dr. Raston, the idea of using a popup/floating box for the tooltips appears like a better option. Now the screen can stay a static size, highlighting can be removed because the SVG can be displayed in the popup.
